
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np

array = np.arange(10)# (0 to 9)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array = np.arange(2,11)
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [4]:
# reshape
# 3*3

array = np.arange(1,10)
array

reshaped_array = array.reshape((3,3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [7]:
array_element = reshaped_array[1,1]
array_element

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [10]:

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
# Addition
Addition = array1 + array2
# subtraction
subtraction = array1 - array2
# multiplication
multiplication = array1 * array2
# Division
Division = array1 / array2


array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [26]:
array = np.array([1, 2, 3, 4, 5])

array.sum()


15

In [27]:
array.mean()


3.0

In [28]:
array.std()

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [19]:
array = np.array([1, 2, 3, 4, 5, 6])
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [35]:
random_array = np.random.randint(1,100, size = (5,5))
random_array

array([[ 8, 82, 13, 73, 93],
       [76, 13, 27, 22, 50],
       [44, 73,  4,  3,  1],
       [84, 50, 89, 95,  3],
       [62, 33, 32, 51, 68]])

Replace all values in the sub-array with a specific value.


In [37]:
#           [raw:col,all : col]
random_array[1:4,: ] = 10
random_array

array([[ 8, 82, 13, 73, 93],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [62, 33, 32, 51, 68]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [41]:
array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
array
array[[1,3],:]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [48]:
array = np.array([0,1,2])
array

# Tile:
#                         
new_array = np.tile(array,(3,1))
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [51]:
values = np.arange(3)

array_2d = np.tile(values, (3, 1))

print(array_2d)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [ ]:
array_2d = np.array([[0, 1, 2],
                     [0, 1, 2],
                     [0, 1, 2]])

array_1d = np.array([1, 2, 3])

result = array_2d + array_1d

print(result)

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [61]:
random_array1 = np.random.randint(1,100,size = (3,3))
random_array1

array([[33, 78, 57],
       [30, 45, 83],
       [57, 57, 50]])

In [62]:
random_array2 = np.random.randint(1,100,size = (3,3))
random_array2

array([[29, 46, 88],
       [84, 50, 79],
       [94, 86, 49]])

In [60]:
# hstack and vstack:
# split horizontally:
concatenate_horizontally = np.hstack((random_array1,random_array2))
concatenate_horizontally


array([[94, 97, 88,  8, 35, 16],
       [ 8, 54, 52, 34, 23, 87],
       [50, 48, 94, 22, 64, 59]])

In [63]:
# Split Vertically:
concatenate_vertically = np.vstack((random_array1,random_array2))
concatenate_vertically

array([[33, 78, 57],
       [30, 45, 83],
       [57, 57, 50],
       [29, 46, 88],
       [84, 50, 79],
       [94, 86, 49]])

In [69]:
# Split: hsplit & vsplit:

splitted_array = np.hsplit(concatenate_horizontally,2)
splitted_array

[array([[94, 97, 88],
        [ 8, 54, 52],
        [50, 48, 94]]),
 array([[ 8, 35, 16],
        [34, 23, 87],
        [22, 64, 59]])]

In [72]:
# indexing:
print(splitted_array[0])
print(splitted_array[1])

[[94 97 88]
 [ 8 54 52]
 [50 48 94]]
[[ 8 35 16]
 [34 23 87]
 [22 64 59]]


In [67]:
splitted_array = np.vsplit(concatenate_vertically,2)
splitted_array

[array([[33, 78, 57],
        [30, 45, 83],
        [57, 57, 50]]),
 array([[29, 46, 88],
        [84, 50, 79],
        [94, 86, 49]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [82]:
array = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
count_dict = {}
for i in array:
    if i in count_dict:
        count_dict[i] += 1
    else:
        count_dict[i] = 1
count_dict


{1: 7, 2: 5, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 22: 1, 21: 1}

In [85]:
mode = None
max_count = 0
for num in set(array):
    if count > max_count:
        mode = num
        max_count = count

print("Mode:", mode)

Mode: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

